### ISSUE TITLE
Add growing rate for states

### ISSUE THREAD

**Issue by RiLeone** [RiLeone/warbot#3]
States which are not involved in a battle should still evolve at each turn, for example by growing in population by some percentage.

**Comment by SGE-MagHead** [comment]
Would be also interesting to assign a set of resources ("can be one variable or set") randomly at the beginning of the turn  to every state to use to determine the growing rate, as the state fight resources are transferred to the winner etc. 
In a second moment could be made way more complicated to add an additional layer of depth to the simulation/game
